config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todos do 
    resources :tasks, only: [:index, :new, :create]
    resources :favourites, only: [:new, :create]
  end
  resources :tasks, only: [:show, :edit, :destroy]
  root "todos#index"
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/models/favourite_list.rb
class FavouriteList < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo
  validates :description, presence: true
  validates :description, length: { maximum: 40}

  def done?
    !done_at.blank?
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  attr_accessor :public
  belongs_to :user
  has_many :tasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :email, presence: true, uniqueness: true
  validates :password, length: { in: 6..20 }
  has_many :todos, dependent: :destroy
  has_many :favourites, through: :todo, dependent: :destroy
  has_many :tasks, through: :todo


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatables

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/favourites_controller.rb
class FavouriteController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]
  # before_action :set_todo

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
    @todo = Todo.find(params[:todo_id])
  end

  def create
    task = Task.new(task_params)
    todo = Todo.find(params[:todo_id])
    task.todo = todo
    task.save
    redirect_to todo_path(todo)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:description, :done)
  end



  # def create
  #   @task = Task.create(task_params)
  #   redirect_to @todo_list
  # end

  # private

  # def set_todo
  #   @todo_list = Todo.find(params[:todo_id])
  # end

  # def task_params
  #   params.require(:task).permit(:description, :done, :todo_id)
  # end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [ :show, :edit, :update, :destroy ]

  # def index
  #   @todos= Todo.all
  # end

  # def show
  #   @todo = Todo.find(params[:id])
  # end

  # def new
  #   @todo = Todo.new 
  # end

  # def edit
  #   @todo = Todo.find(params[:id])
  # end

  # def update
  #   @todo = Todo.find(params[:id])
  #   @todo.update(params[:todo])
  # end
  







  def index
    @todos = Todo.all
  end

  def show
    @tasks = @todo.tasks
    @task = Task.new
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id
    @todo.save
    redirect_to todos_path
  end

  def edit
  end

  def update
    @todo.update(todo_params)
    redirect_to todo_path(@todo)
  end

  def destroy
    @todo.destroy
    redirect_to todos_path
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:public, :user_id, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @tasks = Task.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TesteAutoseg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My todo list", "#", class: "dropdown-item" %>
            <%= link_to "Favourite list", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tasks/_index.html.erb
<h1>My tasks</h1>

<ul id="tasks">
  <% @tasks.each do |task| %>
    <li>
      <% if task.done %>
        <i class="fa fa-check-square-o"></i>
      <% else %>
        <i class="fa fa-square-o"></i>
      <% end %>
      <%= link_to task.description, task_path(task.id) %>
      ·
      <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.description}?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<hr>

<%#= link_to new_task_path do %>
  <%
=begin%>
 <i class="fa fa-plus"></i> Add a new task 
<%
=end%>
<%# end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form', task: @task %>

<hr>
<%= link_to tasks_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul id="tasks">
  <% @tasks.each do |task| %>
    <li>
      <% if task.done %>
        <i class="fa fa-check-square-o"></i>
      <% else %>
        <i class="fa fa-square-o"></i>
      <% end %>
      <%= link_to task.description, task_path(task.id) %>
      ·
      <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.description}?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<hr>

<%= link_to new_task_path do %>
  <i class="fa fa-plus"></i> Add a new task
<% end %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%#= render 'form', task: @task %>

<%= form_for [@todo, @task] do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :done %> Done
      </label>
    </div>
  <% end %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<hr>
<%#= link_to tasks_path do %>
  <%
=begin%>
 <i class="fa fa-history"></i> Back to list 
<%
=end%>
<%# end %>

app/views/tasks/show.html.erb
<%= link_to edit_task_path(@task.id), class: 'pull-right btn btn-default' do %>
  <i class="fa fa-pencil"></i> Edit this task
<% end %>

<h1><%= @task.description %></h1>

<% if @task.done %>
  <i class="fa fa-check-square-o"></i> This task is done
<% else %>
  <i class="fa fa-square-o"></i> This task is not done yet
<% end %>

<hr>
<%= link_to @task.todo do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/todos/_form.html.erb
<%= form_for (@todo) do |f| %>

  <div class="checkbox">
    <%= f.check_box :public %> Make public list
      <%#= f.label :public %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

    <%#= f.association :task, include_hidden: false %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>


<%
=begin%>
 <%= simple_form_for [@cocktail, @dose] do |f| %> 
<%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %> 
<%
=end%>

app/views/todos/edit.html.erb
<h1>Edit todo</h1>

<%= render 'form', todo: @todo %>

<hr>
<%= link_to todos_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/todos/index.html.erb
<h1>My Todo Lists</h1>

<ul id="todos">
  <% @todos.each do |todo| %>  
   <%# raise%> 
    <li>
      <%= link_to todo.description, todo_path(todo.id) %>
      
      <%= link_to todo_path(todo.id), method: :delete, data: { confirm: "Delete #{todo.id}?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<hr>

<%= link_to new_todo_path do %>
  <i class="fa fa-plus"></i> Add a new todo
<% end %>

app/views/todos/new.html.erb
<h1>New Todo List</h1>

<%= render 'form', todo: @todo %>

<hr>
<%= link_to todos_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/todos/show.html.erb
<div class="show tasks my-4 p-4"> 
  <h3> Tasks </h3> 
  <%= render "tasks/index", tasks: @tasks %>
</div>  

<%= link_to edit_todo_path(@todo.id), class: 'pull-right btn btn-default' do %>
  <i class="fa fa-pencil"></i> Edit this todo
<% end %>

<%= link_to todos_path do %>
  <i class="fa fa-history"></i> Back to list
  <%= link_to "new task", new_todo_task_path(@todo) %> 
<% end %>